import = ['~/.config/alacritty/catppuccin/catppuccin-mocha.toml']

# Theme
[font]
size = 24.0
offset = { y = 7, x = 0 }

[font.bold]
family = "Agave Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Agave Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

[window]
opacity = 0.75
decorations = "none"
startup_mode = "Maximized"
