import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]


# Theme
[font]
size = 24.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Medium Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window]
opacity = 0.90
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
